kind:
  version: v0.12.0
  kube_version: v1.23.4
registry:
  enable: true
  ssl: true
tools:
  kubectl:
    version: v1.23.4
  oc:
    version: 4.3.5
  operator_sdk: 
    version: v1.18.1
  olm:
    version: v0.20.0
